FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./
ENV NODE_ENV=production
EXPOSE 4321

# Aceitar host para Node adapter ouvir em 0.0.0.0
ENV HOST=0.0.0.0

CMD ["node", "./dist/server/entry.mjs"]
